### PR TITLE
Angular support in templates and sdk lib

### PR DESCRIPTION
**Pull request by oniseijin**
This has angular templates for blades, unit-test, acceptance-tests, aspects. These are all interface identical to the knockout templates. All unit tests and acceptance pass, and had a few rounds of experiments.  

Has full scope and controller exposure in acceptance tests.

Also includes angular 1.5 and angular mocks in the JavaScript sdk lib as these are needed for angular and acceptance tests respectfully.

### CODE REVIEW

**Comment by oniseijin** [comment]
Build failure seems to be unrelated environment variable settings on travis for JDK7 and JDK8. Template additions and additional libraries aren't part of the standard tests as is..

**Comment by oniseijin** [comment]
Build seemed to not like something about the angular.js lib, although, functionally everything works fine...

**Comment by dchambers** [comment]
Thanks for pull-request @oniseijin.

> Build seemed to not like something about the angular.js lib, although, functionally everything works fine...

Yeah, it's failing on the `jsdoc` stage. It doesn't seem to like this construct:

~~~js
 * @param  {{
 *           minFrac, // the minimum number of digits required in the fraction part of the number
 *           maxFrac, // the maximum number of digits required in the fraction part of the number
 *           gSize,   // number of digits in each group of separated digits
 *           lgSize,  // number of digits in the last group of digits before the decimal separator
 *           negPre,  // the string to go in front of a negative number (e.g. `-` or `(`))
 *           posPre,  // the string to go in front of a positive number
 *           negSuf,  // the string to go after a negative number (e.g. `)`)
 *           posSuf   // the string to go after a positive number
 *         }} pattern
~~~

I imagine deleting that particular jsdoc annotation will fix the problem.

**Comment by oniseijin** [comment]
Fixed all jsDoc related error messages, but build locks down without clear reason

brjs-sdk:copyBrowsers
:brjs-sdk:jsdoc
Successfully created new app 'jsdoc-tmp-app'
 /home/travis/build/BladeRunnerJS/brjs/brjs-sdk/apps/jsdoc-tmp-app
Successfully deployed 'jsdoc-tmp-app' app
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated

**Comment by dchambers** [comment]
Hi @oniseijin, yes I tried building on my machine, and it didn't finish after three hours of elapsed time!

I had a look at the jsdoc documentation and noticed it had an [`excludePattern` feature](http://usejsdoc.org/about-configuring-jsdoc.html#specifying-input-files), and then found out that we've already been using this feature all along in [`jsdoc-conf.json`](https://github.com/BladeRunnerJS/brjs/blob/c642874/brjs-sdk/sdk/jsdoc-toolkit-resources/jsdoc-conf.json#L11). Adding this line to the `exclude` block fixed it for me:

~~~json
 "sdk/libs/javascript/angular",
~~~

If you can do the same in your fork and re-push we should be good to start testing this on our side.

**Comment by dchambers** [comment]
Dev reviewed :+1:

**Comment by thecapdan** [comment]
I had a quick look at this as I was preparing the upcoming release.

It is a great starting point, and works nicely for creating an angular aspect/blade inside an existing app.

I noticed when creating a new app from the command line, i.e.

```
brjs create-app myapp --template angular
```

I got an error since there was nothing under sdk/templates/angular/app.

The work done under this PR in itself works great and will go into the release for creating angular blades and aspects, but some more work down the road to finish it off would be awesome. I'll create a new issue.

**Comment by oniseijin** [comment]
Thanks. Logically speaking, since the aspect is working, I would this it isnt far from creating a full app. I looked under the app default for app, and it was basically blank. My guess: create a folder call app under angular, and it may use the aspect template to create it; will try later if no one else attempts it.

**Comment by thecapdan** [comment]
Yup, for the app its that easy:) I might try and get that in for the release, to make it easier for anyone else using it for the first time when creating an angular app. there's a few other templates todo (eg bladesets) which we can leave for a later date

**Pull request merged**
