### PR TITLE
Added a normaliseXML() function for ensuring the name of the test suite ...

### LINKED ISSUE #825: Can't run tests with --report flag on some IE11 machines
we get:

Writing HTML reports to ../test-results/html.
ERROR: Errors while applying transformations: Fatal error during transformation
Error:
Error running tests.
Caused by: javax.xml.transform.TransformerException: D:\go\pipelines\ct-brjs-develop\ct-core\test-results\html\Mozilla\50_(Windows_NT_61;_WOW64;_Trident\70;_rv:110)_like_Gecko__Windows\package-frame.html (The filename, directory name, or volume label syntax is incorrect)

This may also impact running tests via the dashboard, as it also generates html reports

### PR DESCRIPTION
**Pull request by ioanalianabalas**
...matches the file name.

Fixes #825.

### CODE REVIEW

**Comment by ioanalianabalas** [comment]
@dchambers I have added the comment.

**Comment by dchambers** [comment]
@avsmithy, did you mean to close this pull-request without merging?

**Comment by avsmithy** [comment]
@dchambers no, sorry I closed on Huboard without merging by mistake. Thanks for catching it!

**Comment by avsmithy** [comment]
@ioanalianabalas when I run UTs it works as desired, however running ATs (or UTs+ATs) causes the same error as before.

Secondly, if you try and run `brjs test --report .\libs\javascript\br-core ATs` there's a different error as there are no ATs: `brjs\brjs-sdk\test-results\xml does not exist.`. Is this related?

**Comment by ioanalianabalas** [comment]
@avsmithy, the AT's shouldn't throw the transformation issue any longer.

As for the case where we have no ATs, I will have a look at that now.

**Comment by ioanalianabalas** [comment]
@avsmithy, corrected the regex so that " are not part of the test suite name. That should work now.

I will also be getting started on the no ATs case.

**Comment by ioanalianabalas** [comment]
@avsmithy, the second scenario works now as well.

**Comment by andyberry88** [comment]
@ioanalianabalas This looks good. Apart from the name of your test isn't very descriptive. Can you rename it to something more meaningful and then this can go into `test`.

**Comment by ioanalianabalas** [comment]
@andyberry88 I have now renamed the test to normaliseXMLSoTestsuiteNameCorrespondsToFileName and I will move the pull request into `ReadyForTest

**Comment by andyberry88** [comment]
:+1: Much better :smile:

**Comment by avsmithy** [comment]
@ioanalianabalas can you fix the merge conflict please? 

Tested and happy to merge.

**Comment by ioanalianabalas** [comment]
@avsmithy the merge conflict has been resolved.

**Pull request merged**
