### PR TITLE
NumericValidator validates floats and negatives

### PR DESCRIPTION
**Pull request by avsmithy**
fixes https://github.com/BladeRunnerJS/brjs/issues/1152

### CODE REVIEW

**Comment by dchambers** [comment]
Dev reviewed :+1:

**Comment by avsmithy** [comment]
The strings `".1"` and `"1."` will fail this regex. If parsed into a number before validating, they will be converted to `0.1` and `1` respectively and therefore pass.

**Comment by dchambers** [comment]
Hi @avsmithy, I just took a look at the code and it's both. The `vValue` parameter has a _variant_ type, hence the `v` prefix. Makes things more painful doesn't it!

**Comment by avsmithy** [comment]
@dchambers Thanks for the info, I've made some changes if you'd like to review them.

**Pull request merged**
