### PR TITLE
Changed the redirection path if URL is from Apache Cordova.

### LINKED ISSUE #923: Locale redirection doesn't work in built app when deployed using Apache Cordova
@soruban has found that, when using Apache Cordova, 'index.html' redirects to the wrong URL in the exported app because the `host` variable within that page contains an unneeded slash. I've asked @jngo00 to provide details about the value of `host` when using Apache Cordova.

### PR DESCRIPTION
**Pull request by ioanalianabalas**
Fixes #923.

### CODE REVIEW

**Comment by dchambers** [comment]
I don't like this _pull-request_ as `LocaleUtility.js` shouldn't have any code in it to do with Apache Cordova. Can this not be fixed in a generic way?

**Comment by ioanalianabalas** [comment]
@dchambers, thank you for your feedback. I have now changed the name of the variable as it is not Cordova-specific.

**Comment by avsmithy** [comment]
@ioanalianabalas I've modified the test case, it should work on Cordova once this passes.

**Comment by dchambers** [comment]
I think in general the use of comments is sign that the code is unreadable, and could be made easier to read.

**Comment by avsmithy** [comment]
@dchambers `.endsWith` is ES6. I've tried to improve the readability of the method.

**Comment by dchambers** [comment]
@avsmithy, yes, the method is now infinitely more readable than it was before :+1:

**Comment by avsmithy** [comment]
Static file and Cordova builds are now working.

**Pull request merged**
