### PR TITLE
Feature add ignore case to presenter OptionsNodeList

### PR DESCRIPTION
**Pull request by janhancic**

### CODE REVIEW

**Comment by andyberry88** [comment]
@dchambers what happened to this feature request? Did you create another pull request?

**Comment by dchambers** [comment]
@andyberry88,  it seems like some of the comments for this issue have been deleted. If I remember correctly I requested some changes before merging which were never done, so I eventually closed the issue.

**Comment by andyberry88** [comment]
@dchambers based on this PR are you able to recall the changes that needed to be made? @janhancic could you re-open this pull request if @dchambers provided the suggested changes?

**Comment by dchambers** [comment]
@andyberry88, it's been a long time, and I no longer remember what my feedback was last time, so I've just dev-reviewed afresh.

**Comment by andyberry88** [comment]
I've re-applied the commits and opened https://github.com/BladeRunnerJS/brjs/pull/1431. I've also made changes following your feedback @dchambers.

**Pull request closed without merging**
