### PR TITLE
Plugin interface review

### PR DESCRIPTION
**Pull request by dchambers**
This pull-request contains the changes for the [ContentPlugin](https://github.com/BladeRunnerJS/brjs/wiki/Plugin-Interface-Review#the-contentplugin-interface) and the [MinifierPlugin](https://github.com/BladeRunnerJS/brjs/wiki/Plugin-Interface-Review#the-minifierplugin-interface) described within the [Plugin Interface Review](https://github.com/BladeRunnerJS/brjs/wiki/Plugin-Interface-Review).

### CODE REVIEW

**Comment by dchambers** [comment]
@andyberry88, can you dev-review this when you get a chance please. I've already confirmed that it doesn't conflict with #1160, so no worries there ... :8ball:

**Comment by dchambers** [comment]
Moving this to `ReadyForTest` as this has been waiting for dev-review for a week now.

**Comment by andyberry88** [comment]
Sorry @dchambers I know this was waiting on me. Had a brief look at this and all look OK.

**Comment by andyberry88** [comment]
Closing this PR as the branch has been merged into `moving-api-classes` so these changes will be included in another PR.

**Pull request closed without merging**
