### PR TITLE
Modified brjs so that paths are converted to Cygwin format for the java ...

### LINKED ISSUE #1150: in vanilla cygwin "brjs" script does not run
Issue:

waqask@WAQASK-T430 /cygdrive/c/Users/waqask/Desktop/BladeRunnerJS/sdk
$ ./brjs start
Error: Could not find or load main class org.bladerunnerjs.runner.CommandRunner

The reason the script behaves like this is because Java under cygwin cant map "/cygwin/c/users/somedir" or "/c/users/somedir" to "C:\Users\somedir". 

When you run the "brjs.cmd" script, the cp provided has the actual "C:\", hence that will work.

sJira: http://yourls.caplin.com/7

### PR DESCRIPTION
**Pull request by ioanalianabalas**
Fixes #1150.

### CODE REVIEW

**Comment by avsmithy** [comment]
Could we use an if statement to detect Cygwin instead?

```
if [ "$(expr substr $(uname -s) 1 6)" == "CYGWIN" ]; then
	# Cygwin version
	java $JAVA_OPTS -cp "`cygpath -wp $BRJS_CLASSPATH`" org.bladerunnerjs.runner.CommandRunner "`cygpath -wp $SCRIPT_DIR`" "$@"
else
	# UNIX & GitBash version
	java $JAVA_OPTS -cp "$BRJS_CLASSPATH" org.bladerunnerjs.runner.CommandRunner "$SCRIPT_DIR" "$@"
fi
```

**Comment by avsmithy** [comment]
I needed to run dos2unix to fix line endings before it would work in Cygwin. Can we do this and check it in?

**Comment by avsmithy** [comment]
Also, we should link to `#!/bin/bash` rather than `#!/bin/sh`.

**Comment by andyberry88** [comment]
> Also, we should link to #!/bin/bash rather than #!/bin/sh.

Not sure about this one. `/bin/sh` is present in pretty much all *nix systems, `/bin/bash` is not, I imagine it could not be in *nix like environments. So long as the script is `POSIX` compliant it should run anywhere with `#/bin/sh`.

**Comment by avsmithy** [comment]
`/bin/sh` can be a [symlink to the default shell](http://askubuntu.com/a/141932), so you could run into inconsistencies. You're correct though, if the script is `POSIX` compliant it should work fine everywhere.

**Comment by avsmithy** [comment]
The new if statement has been tested in Mac, Cygwin and MinGW.

**Comment by thanhc** [comment]
tested and verified on windows/mac/linux

**Pull request merged**
