### PR TITLE
Seperate plugins into separate projects

### PR DESCRIPTION
**Pull request by andyberry88**
PR for #747 

- starting to move plugins into their own separate projects
- temporarily moving all brjs-core tests into a separate project so we can slowly move plugin specific tests into plugin projects and core tests back into brjs-core
- removing the need for `workspace` and `build-resources` directories in `brjs-sdk`
- fixing Gradle config so it doesnt run tasks that dont need to be run

**This is not 100% complete but it would be good to get it merged in since we're otherwise going to forever have merge conflicts**

### CODE REVIEW

**Comment by dchambers** [comment]
Dev reviewed :+1:

**Comment by thecapdan** [comment]
No matter what I try - I can't get this branch to work. It seems to assemble correctly - but when i try to run any brjs command i get the following message:

```
Error: Could not find or load main class org.bladerunnerjs.runner.CommandRunner
```

I check the libs directory and there is no java folder (not sure if this is by design!). Moving back to dev

**Comment by andyberry88** [comment]
@thecapdan The problem above was caused by the Gradle config that now auto imports all sub projects only working on Linux due to the way it uses file paths to calculate the project name. It should now be fixed.

**Comment by thecapdan** [comment]
working now on windows. builds successfully, tests pass. merging

**Pull request merged**
