### PR TITLE
Add Polling file observer

### LINKED ISSUE #1283: McAffee virus scanner makes the app take 20+ mins to load
In the process of upgrading to CT4 / Motif 2.1.1. When running ./brjs serve and navigating to localhost:7070/dashboard it never loads. After around 25mins the browser will redirect to localhost:7070/dashboard/en but the dashboard still does not load. Navigating directly to /dashboard/en also has the some result. CPU profile screenshot from VisualVM is attached below. Task manager shows that the java process is using around 25% CPU for the whole time ./brjs serve is running and is the only process using a significant amount of CPU. Running ./brjs serve --debug shows that brjs looks to be constantly trying to resolve dependencies. 

BRJS version: 0.14.3.0
CT version: 4.0.3
Java version: 1.8.0_40 64bit
JAVA_OPTS: -Xms1024m -Xmx4096m
OS: Windows 7 Enterprise 64bit

cpu profile

I have also tried downloading the latest version of BRJS from the website (0.15.1.0) and have the same issue though it has a different CPU profile:

cpu profile 15

### PR DESCRIPTION
**Pull request by andyberry88**
Adding a polling file observer that can be enabled via `brjs.conf`.

Fixes #1283.

### CODE REVIEW

**Comment by andyberry88** [comment]
>  can you explain the inter-play between the 1 second polling time (e.g. new FileAlterationMonitor(1000)) and the 1 minute sleep time (e.g. Thread.sleep(60000))?

The Apache Commons file monitor itself is a thread while has an internal check/sleep cycle. Since the API for our File observer is also a thread, and we don't need to do anything once the file monitor is started, we wait continually. Ideally we should probably re-look at the file observer API and not force it to be a thread.

**Comment by dchambers** [comment]
> The Apache Commons file monitor itself is a thread while has an internal check/sleep cycle. Since the API for our File observer is also a thread, and we don't need to do anything once the file monitor is started, we wait continually. 

Okay, so the interface is now wrong then I guess. It sounds like we should remove any threading concerns from the interface, and leave such details to the individual file modification observer?

**Comment by dchambers** [comment]
I've now finished dev-reviewing, and apart from the additional thread we now have (which can be dealt with later), I'm now happy that this is ready to merge.

**Comment by andyberry88** [comment]
> Okay, so the interface is now wrong then I guess. It sounds like we should remove any threading concerns from the interface, and leave such details to the individual file modification observer?

Yep. I imagine an interface with `start` and `stop` is probably adequate. Each observer can then decide how it then spawns the new thread.

**Comment by thanhc** [comment]
tested, that by default watching method is used, changed to polling and verified that the default 1 sec poll is used, then overrided the polling and verified that this is used, checked with running --debug to see what time is being used and changing a file and seeing how long it takes to be picked up.

Also changed the dependencies in a .js file by adding a new require and refreshed app the new file is only included after the polling time.

**Pull request merged**
