### PR TITLE
Allow templates to be embedded in index page

### PR DESCRIPTION
**Pull request by dchambers**
This pull-request is dependent on #1338 (first relevant commit is e7286b6). It fixes the first two optional parts of #1116.

### CODE REVIEW

**Comment by dchambers** [comment]
@andyberry88, I moved to `ReadyForTest` on the assumption that you have finished dev reviewing this issue?

**Comment by andyberry88** [comment]
@dchambers Yep, just that one suggestion.

**Comment by thanhc** [comment]
there are some test failing in CT with the HTML resource bundling change, ct-workbench and ct-presenter
one of the test failing is:
 Connection Status Editor Workbench Tests. Checks all buttons are available and 'OK' is the initial state
with the following error:
The 'caplin.workbench.connection-editor' template contained more than one root node -- use getTemplateFragment() instead.

**Comment by thanhc** [comment]
In IE we're actually getting more test failures with the same error message regarding template containing more than one node., plus other failures.

In IE8 we're gettign type error's: object doesn't support this property or method

**Comment by thanhc** [comment]
In IE8 when adding the santizeHTML to the innerHTML some template tags aren't being added causing failures in IE8

**Comment by thanhc** [comment]
Found an issue with using <@html.bundle@/> tag when you have a template with multiple templates then we dont seem to fix the auto wrapped templates as a result we get the "template contained more than one root node" error.  I have made changes to the it-app so that itapp.itbladeset.itblade.view has two templates in that file, then added the <@html.bundle@/> tag to the index.html (commented out), the app loads correctly when this is commented out but fails when you uncomment it.  I tried to write the following spec test but it didn't seem to catch the issue:

@Test
	public void multiTemplatesAreLoadedCorrectlyWhenEmbededInIndexPage() throws Exception {
		given(aspect).containsFileWithContents("index.html", "'<html><head><@html.bundle@/></head> hello world  </html>'")
			.and(aspect).containsResourceFileWithContents("html/view.html", "<template id='appns.view'>TESTCONTENT</template> <template id=appns.view-2>BOB</template>");
		when(aspect).requestReceivedInDev("html/bundle.html", response);
		then(response).containsOrderedTextFragments("TESTCONTENT", "BOB");
	}

**Comment by andyberry88** [comment]
@thanhc The issue with the IT-app is fixed in fbd9dd2.

**Comment by thanhc** [comment]
@andyberry88 looks better, the templates are now being separated out correctly., however if in the template I use i18n tokens e.g. <label>@{ct.grid.refine.refinersummary.filters}</label> then these aren't being replaced

**Comment by andyberry88** [comment]
@thanhc The i18n token issue is fixed in the latest commits. We now replace i18n token in embedded templates on the server. If it's loaded via XHR it will continue to be replaced in the client.

**Pull request merged**
