### PR TITLE
Deprecate base tag and don't display locale in URL for single-locale apps

### PR DESCRIPTION
**Pull request by dchambers**

### CODE REVIEW

**Comment by dchambers** [comment]
This is probably going to break until [snapshots.repository.codehaus.org](http://snapshots.repository.codehaus.org/) starts working again, but can be dev-reviewed now anyway.

**Comment by dchambers** [comment]
Replicating took a bit of effort. Here are some notes in case I need to do this again. I started by running these commands:

```bash
./brjs create-app app1
./brjs j2eeify app1
./brjs serve
```

after which I confirmed the app worked before enabling authentication by adding this to the `web.xml` of my new app:

```xml
<session-config>
	<session-timeout>10000</session-timeout>
</session-config>

<security-role>
	<role-name>user</role-name>
</security-role>

<security-constraint>
	<web-resource-collection>
		<web-resource-name>Application</web-resource-name>
		<url-pattern>/*</url-pattern>
	</web-resource-collection>
	<auth-constraint>
		<role-name>user</role-name>
	</auth-constraint>
</security-constraint>

<security-constraint>
	<web-resource-collection>
		<web-resource-name>Login Section</web-resource-name>
		<url-pattern>/login/*</url-pattern>
	</web-resource-collection>
</security-constraint>
```

after which I refreshed the browser and confirmed that a username was required, and then updated `app.conf` to add a second locale, and confirmed the app still worked, but contained the locale within the URL.

By adding this to `web.xml`:

```xml
<login-config>
	<auth-method>FORM</auth-method>
	<realm-name>BladeRunnerLoginRealm</realm-name>
	<form-login-config>
		<!-- TODO: see if it's possible to have the same config for both Tomcat and Jetty -->
		<!-- Tomcat does not 302 redirect to /APP_CONTEXT/login as search engines don't like 302's but Jetty does hence the two form-login-pages -->
		<!-- start-env: dev -->
		<form-login-page>/login/</form-login-page>
		<!-- end-env -->
		<!-- start-env: prod
		<form-login-page>/login/unbundled-resources/redirect.html</form-login-page>
		end-env -->
		<form-error-page>/login/</form-error-page>
	</form-login-config>
	<auth-constraint>
		<role-name>*</role-name>
	</auth-constraint>
</login-config>
```

and restarting the server I was able to observe the browser forward to the `/app1/login` page, but this gave me a 404 since new apps don't have login aspects.

By copying the entire `login-aspect` from 'fxtrader' to my new app, I was finally able to replicate.

**Comment by dchambers** [comment]
Okay, this seems to be an issue inside CTs login aspect. By replacing the login aspect with a single `index.html` file containing the following content, I was able to login just fine:

```html
<!DOCTYPE html>
<form class="formLogin" id="formLogin" action="j_security_check">
	<input name="isLoginPage" type="hidden" value="login-page" />
	<input id="txtUsername" class='username' type="text" name="j_username" size="15"
	 value="user1@caplin.com" autocorrect="off" autocapitalize="off"/>
	<input id="txtPassword" class='password' type="password" name="j_password" size="15"
	 value="password" autocorrect="off" autocapitalize="off"/>
	<button type="submit">Login</button>
</form>
```

I guess this will be caused by our changes to the base tag, or the need to now prefix requests for `unbundled-resources` with `../` (e.g. via the `<@unbundled-resources@/>` tag).

**Comment by thecapdan** [comment]
Thanks @dchambers - I'll retest and see if i can work out how we can word this in our release notes if it's going to effect users outside of CT

**Comment by dchambers** [comment]
Hi @thanhc, I can now see where the confusion has come from regarding this issue and #1180. To clarify, there are 3 distinct locale related bits of work that have been done:

  1. Not displaying the locale for single-locale apps (this _pull-request_).
  2. Deprecating the `<@base.tag@/>` tag (this _pull-request_).
  3. Making locale handling more flexible (#1180).

Unfortunately, 1 and 2 had to be done together as they are affected by each other. I've now renamed the title of this _pull-request_ to make that clearer.

**Comment by thanhc** [comment]
After testing this issue, here are my findings:
- In the brjs template the index.html still has includes the <@base.tag@/> (if we are deprecating this then we should remove it from our templates)
- upgrading CT to use this version of brjs is not so easy, as its not just a case of find and replace, there are a few request to unbundled-resources and servlets which all need the ../ added to the front of them for them to work in a multi-locale app, in addition to this there are some places where there is a function which adds a part of the url in such as the popouts: var ticketPopout = new caplin.popout.Popout('popout/'); which requires adding ../ in front of it.
- Also we needed to make a change to a webcentric js library file to also include the ../ as this makes a request to servlet/webcentric/logins/

**Comment by dchambers** [comment]
We can get around the backwards compatibility issue by allowing `enableDeprecatedBaseTag: true` to be added to `app.conf`, in which case we will:

  1. Start emitting a `<base href="../"/>` tag again (alongside the deprecation message) when `<@base.tag@/>` is used.
  1. Stop prefixing versioned bundle paths with `../`.

@andyberry88 / @james-shaw-turner: are you happy with this?

**Comment by andyberry88** [comment]
Do we need to get around the backwards compatibility issue? It's a relatively small change that's going to have to be made at some point if we are deprecating the feature and removing it at some point. I can see a `enableDeprecatedBaseTag` sticking around forever and just becoming bloat we don't need only to save a small amount of time.
My preference is to spend the time investing in docs explaining why we have `../` in the paths and how developers can use the `undbundled-resources` tag and `AppMeta` service to automatically prepend that if the app is using more than 1 locale.

**Comment by adamshone** [comment]
@andyberry88 Yes, I think we do have to think about the backwards compatibility issue. Upgrading to BRJS introduced the "/en" to the application URL, which meant that our clients were required to find and pre-pend an extra "../" to every relative path in their applications. They will justifiably be annoyed if we put them through this process to upgrade to CT 4.0.0, and then make them change it all back again when they upgrade to CT 4.0.2. It makes it look like we don't know what we're doing and gives a bad first impression of BRJS.

**Comment by dchambers** [comment]
@adamshone, yes, we do need to properly evaluate all the options so as to cause as little upgrade pain as possible. Although the need for these changes was known about for quite some time, CT releasing on a pre 1.0 release of BRJS has just made our ability to complete these stories that much more difficult.

**Comment by andyberry88** [comment]
`Upgrading to BRJS introduced the "/en" to the application URL, which meant that our clients were required to find and pre-pend an extra "../" to every relative path in their applications.`

We should get people to migrate to using the meta service anyway. If single locale apps aren't going to have the `/en` and multi locale apps will then the `../` won't always be required. Do we know how many people are going to have to make these changes or whether most of it is contained within the motif codebase?

**Comment by adamshone** [comment]
They tend to all do logout a bit differently, but apart from that most of the changes are in the motif. I had another look at it and actually the references to "unbundled-resources" don't seem to have "../" in most cases. I think we must have removed that in favour of the @base-tag@. 

I had a chat with Dom and he reckons that if we change it so that the locale is never in the URL, even in a multi-locale app, then the upgrade should be painless. We just deprecate the @base-tag@ and change it to be inert, and then all of the existing "unbundled-resources" strings should still resolve correctly.

**Comment by dchambers** [comment]
There are lots of subtleties to this issue:

  1. The `<base/>` tag makes routed SPA apps [really awkward](https://github.com/BladeRunnerJS/brjs/issues/1059) to create.
  1. Having a different URL structure for _single-locale_ and _multi-locale_ apps makes unversioned requests [really awkward](https://github.com/BladeRunnerJS/brjs/issues/692#issuecomment-69958254) to create &mdash; at present we don't even offer a tag or API for making unversioned requests.
  1. Versioned `unbundled-resources` URLs that occur outside of the index page are awkward, but these are necessary for static file deployment.
  1. We have to support unversioned `unbundled-resources` URLs since these sometimes find their way into databases, and since the App-Cache plug-in uses a manifest instead of versioned URLs.
  1. Making unversioned `unbundled-resources` URLs easier to work with than versioned URLs is bad, since it results in slower app start-up times.

Therefore I propose that we make the following changes:

  1. We change multi-locale apps to no longer contain the locale in the URL, and to dynamically load the resources instead.
  1. We ensure versioned URLs are used wherever possible, and add comments explaining why unversioned URLs have been used when they were genuinely needed.

**Comment by dchambers** [comment]
This pull-request is superseded by #1206, which is based off of it.

**Pull request closed without merging**
