### PR TITLE
Moving api classes into API packages

### PR DESCRIPTION
**Pull request by andyberry88**
This is a part fix for #1085 - it also contains the changes from #1161 PR.

### CODE REVIEW

**Comment by thanhc** [comment]
When running brjs serve with this branch I'm getting quite a few error's:
java.lang.ClassNotFoundException: com.caplin.cutlass.servlet.FileServlet
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
java.lang.ClassNotFoundException: com.caplin.cutlass.servlet.FileServlet
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)

as a result the dashboard does not load correctly.

**Comment by andyberry88** [comment]
> When running brjs serve with this branch I'm getting quite a few error's:

This should now be fixed. When I renamed some packages Eclipse hadn't renamed the classpath in some `web.xml`s.

**Comment by mayanks-caplin** [comment]
Clean assemble is not successful. There is a build error as shown on Travis CI.

**Comment by andyberry88** [comment]
Compile errors fixed.

**Comment by andyberry88** [comment]
This is still failing but its due to unreliability in Travis rather than genuine failures.

**Comment by mayanks-caplin** [comment]
Clean assemble is now building successfully on my local machine.

**Comment by andyberry88** [comment]
@mayanks-caplin The issues have all (hopefully) been fixed. This is ready for another look now.

**Comment by mayanks-caplin** [comment]
Retested - working well on local and compiling successfully on travis as well.

**Pull request merged**
