### PR TITLE
improve ErrorMonitor with its own hasError property #1637

### PR DESCRIPTION
**Pull request by mborik**
Improved ErrorMonitor with its own hasError property which indicates if any of the associated fields has error.
Fixed **_addTooltipTo** private method to show tooltips only if it has failureMessage.

### CODE REVIEW

**Comment by thecapdan** [comment]
Hi @mborik 

This has caused some failures in our presenter ATs.

I believe the issue is with _addError is now being called too early. Where you have added this:

```
if (this.hasError.getValue() === true) {
	oTicketErrorProperty._addError(oField);
}
```

It is trying to add the error before the field has been updated. If i comment out oTicketErrorProperty._addError(oField), everything passes (it waits for the observable instead)

Would you mind having a look.

Thanks

**Comment by mborik** [comment]
Hi @thecapdan,
thanks for your comment. I dealt with the issue this morning and I hope that I finally solved it. As you mentioned, I think that issue is in ``fValidationSuccessHandler`` function condition: there is not enough to test only ``hasError`` of the field to true but also there is should be test if field has ``failureMessage`` non-empty.
After that, ATs passing without any problem and also behavior in the application is correct.
I'll push my changes afternoon.

**Comment by thecapdan** [comment]
great. thanks

**Comment by thecapdan** [comment]
hi @mborik , would you mind merging master into your branch, I can then merge this and move it to done. thanks

**Pull request merged**
