### PR TITLE
Exception when app not in known app location 1384

### PR DESCRIPTION
**Pull request by ioanalianabalas**
Fixes issues #1384 and #1342.

An exception is now thrown if the app you are trying to test is not in what BRJS knows to be the apps folder location.

Moreover, log lines will now show the BRJS apps folder and the apps found within.

**This is dependent on #1386**

### CODE REVIEW

**Comment by andyberry88** [comment]
Looks good @ioanalianabalas. Only one minor comment which I've made inline. It might also be worth adding an info log for the location of BRJS itself like you did for the app location. There's also some merge conflicts to fix before it goes into `test`.

**Comment by ioanalianabalas** [comment]
@andyberry88, thank you for your feedback. I have now merged in develop, removed the dead code and added an info log for the BRJS location. Would you mind having a look at these, please?

**Comment by andyberry88** [comment]
:+1: looks good @ioanalianabalas

**Comment by thanhc** [comment]
@ioanalianabalas can you fix the merge issues, also I've tried to reproduce the two issues this is suppose to fix,  #1384 and #1342. But on develop which already has #1386 I can't reproduce the issues, if I checkout an earlier build then I see the issues, so I'm wondering what this extra pull request is for?

**Comment by ioanalianabalas** [comment]
@thanhc the merge issues have now been fixed.

**Comment by thanhc** [comment]
This isn't quite working, if I run brjs test ../brjs-apps/myapp from the sdk/ then I get an error saying its not an app, but if I run it from the directory above brjs test brjs-apps/myapp then it works, so it seems like its not treating the ../ correctly.

**Comment by ioanalianabalas** [comment]
@thanhc this is now fixed.

**Pull request merged**
