### PR TITLE
Apps separate from sdk 1154

### PR DESCRIPTION
**Pull request by ioanalianabalas**
For #1154.

### CODE REVIEW

**Comment by andyberry88** [comment]
@ioanalianabalas This looks good. It might be worth adding 1 more test to use an entirely different temporary directory rather just the parent file of where BRJS is. You can use the `FileUtils` class to create a temporary directory and use that for the working dir (remember to delete the new temporary dir in your `@After` teardown).

**Comment by ioanalianabalas** [comment]
@andyberry88 I added the test.

**Comment by dchambers** [comment]
@ioanalianabalas, there are merge conflicts you now need to resolve.

**Comment by dchambers** [comment]
@andyberry88, are you happy with the extra test @ioanalianabalas added based on your feedback?

**Comment by dchambers** [comment]
I've dev-reviewed the changes that came after that test and am happy with them.

**Comment by andyberry88** [comment]
Yep. Moved to `ReadyForTest`. Although I'm afraid @ioanalianabalas has some more conflicts to fix.

**Comment by ioanalianabalas** [comment]
@andyberry88 I have fixed the merge conflicts.

**Comment by thanhc** [comment]
seems to have a mixup with what should happen when we have both apss and brjs-apps folders, the warning message and site docs say we use brjs-apps but implementation and also for backwards comp we should use apps

**Comment by andyberry88** [comment]
Both the logging and site docs have been updated

**Comment by thanhc** [comment]
creating an app via the dashboard for the first time is throwing the following error:
Successfully deployed 'ggrtrtg1k' app
Exception in thread "Thread-11" java.lang.NullPointerException
        at org.bladerunnerjs.appserver.AppDeploymentFileWatcher.deployApp(AppDeploymentFileWatcher.java:108)
        at org.bladerunnerjs.appserver.AppDeploymentFileWatcher.checkForNewApps(AppDeploymentFileWatcher.java:83)
        at org.bladerunnerjs.appserver.AppDeploymentFileWatcher.run(AppDeploymentFileWatcher.java:57)

after this creating other apps does not throw the error, but if you restart brjs then the error will be displayed when creating a new app, only seems to happen when brjs is running, using the brjs create-app command does not throw the error.

**Comment by thanhc** [comment]
Also should we prevent people from creating an app called brjs-apps, currently it is possible to create an app with this name and so if you are in this folder and then run create-app it will place the new app in this folder.

**Comment by andyberry88** [comment]
> creating an app via the dashboard for the first time is throwing the following error:

We've probably hardcoded the `apps` dir in the `AppDeploymentFileWatcher`. This should use the BRJS instance to get the apps dir.

> Also should we prevent people from creating an app called brjs-apps

IMO this is a real edge case and you deserve what you get if you do it. Do we also stop people creating folders called `brjs-apps` within an app too?

**Comment by thanhc** [comment]
retested issue and the error no longer occurs when creating app from dashboard when there is no apps folder

**Pull request merged**
