### PR TITLE
Fix IE LocaleSwitcher bug

### PR DESCRIPTION
**Pull request by dchambers**
@thanhc, I think this may fix the bug you've been seeing on Jenkins.

### CODE REVIEW

**Comment by dchambers** [comment]
@thanhc, it turns out that this isn't the only IE8 bug at the moment. I've been investigating IE8-IE10 failures (in presenter ATs) that I'd assumed that I'd caused, but it turns out these were actually introduced somewhere between `0.15.4` and `develop`.

Still investigating...

**Comment by andyberry88** [comment]
@dchambers I haven't had chance to have a proper look at the current failures in IE9 & IE10 but it may be related to the jQuery/Knockout/test utils issue I saw a few weeks ago where Knockout is using jQuery because it's there and globalised but our test utils don't use jQuery for events.

**Comment by dchambers** [comment]
@andyberry88, yes you were right. This has now been fixed in #1337.

**Comment by thanhc** [comment]
looks good, test are now passing in IE8

**Pull request merged**
